AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RegionalIPSet:
    Type: 'AWS::WAFv2::IPSet'
    Properties:
      Description: Regional IPSet for API GW and ALB whitelist
      Name: APIGW-ALB-IPSet
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses:
        - 74.139.161.146/32

  RegionalRuleGroup:
    Type: 'AWS::WAFv2::RuleGroup'
    Properties:
      Name: APIGW-ALB-RuleGroup
      Scope: REGIONAL
      Description: Regional Rule Group for API GW and ALB whitelist
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: RegionalWAFRuleGroupMetrics
      Capacity: 1
      Rules:
        - Name: RuleOne
          Priority: 0
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt RegionalIPSet.Arn
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: regionalwafipsetmetric

  WAFLoggingBucketKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Description: KMS Key for WAF Log Bucket
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: "key-default-1"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Effect: "Allow"
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

  WAFLoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketName: aws-waf-logs-micah1
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !GetAtt WAFLoggingBucketKey.Arn
            BucketKeyEnabled: true

  FMSPolicy:
      Type: AWS::FMS::Policy
      Properties:
        ExcludeResourceTags: false
        PolicyName: REGIONAL-WAF-Policy
        RemediationEnabled: true
        ResourceType: ResourceTypeList
        ResourceTypeList:
          - AWS::ApiGateway::Stage
          - AWS::ElasticLoadBalancingV2::LoadBalancer
        ResourcesCleanUp: true
        SecurityServicePolicyData:
          Type: WAFV2
          ManagedServiceData: !Sub '{"type":"WAFV2",
                                  "preProcessRuleGroups":[{
                                  "ruleGroupType":"RuleGroup",
                                  "ruleGroupArn":"${RegionalRuleGroup.Arn}",
                                  "overrideAction":{"type":"NONE"}}],
                                  "postProcessRuleGroups":[],
                                  "defaultAction":{"type":"BLOCK"},
                                  "loggingConfiguration":{"logDestinationConfigs":["${WAFLoggingBucket.Arn}"]}}'
